//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNO_Client.Proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/UNO_DB")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.BanReport[] BanReportsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.FriendList[] FriendListsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.FriendList[] FriendLists1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.Match[] MatchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] avatarImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isBannedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isLoggedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string verificationTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.BanReport[] BanReports {
            get {
                return this.BanReportsField;
            }
            set {
                if ((object.ReferenceEquals(this.BanReportsField, value) != true)) {
                    this.BanReportsField = value;
                    this.RaisePropertyChanged("BanReports");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.FriendList[] FriendLists {
            get {
                return this.FriendListsField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendListsField, value) != true)) {
                    this.FriendListsField = value;
                    this.RaisePropertyChanged("FriendLists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.FriendList[] FriendLists1 {
            get {
                return this.FriendLists1Field;
            }
            set {
                if ((object.ReferenceEquals(this.FriendLists1Field, value) != true)) {
                    this.FriendLists1Field = value;
                    this.RaisePropertyChanged("FriendLists1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.Match[] Matches {
            get {
                return this.MatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchesField, value) != true)) {
                    this.MatchesField = value;
                    this.RaisePropertyChanged("Matches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] avatarImage {
            get {
                return this.avatarImageField;
            }
            set {
                if ((object.ReferenceEquals(this.avatarImageField, value) != true)) {
                    this.avatarImageField = value;
                    this.RaisePropertyChanged("avatarImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idPlayer {
            get {
                return this.idPlayerField;
            }
            set {
                if ((this.idPlayerField.Equals(value) != true)) {
                    this.idPlayerField = value;
                    this.RaisePropertyChanged("idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isBanned {
            get {
                return this.isBannedField;
            }
            set {
                if ((this.isBannedField.Equals(value) != true)) {
                    this.isBannedField = value;
                    this.RaisePropertyChanged("isBanned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isLogged {
            get {
                return this.isLoggedField;
            }
            set {
                if ((this.isLoggedField.Equals(value) != true)) {
                    this.isLoggedField = value;
                    this.RaisePropertyChanged("isLogged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isVerified {
            get {
                return this.isVerifiedField;
            }
            set {
                if ((this.isVerifiedField.Equals(value) != true)) {
                    this.isVerifiedField = value;
                    this.RaisePropertyChanged("isVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastnames {
            get {
                return this.lastnamesField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnamesField, value) != true)) {
                    this.lastnamesField = value;
                    this.RaisePropertyChanged("lastnames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string verificationToken {
            get {
                return this.verificationTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.verificationTokenField, value) != true)) {
                    this.verificationTokenField = value;
                    this.RaisePropertyChanged("verificationToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BanReport", Namespace="http://schemas.datacontract.org/2004/07/UNO_DB")]
    [System.SerializableAttribute()]
    public partial class BanReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FK_idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.Player PlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan hourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idBanReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FK_idPlayer {
            get {
                return this.FK_idPlayerField;
            }
            set {
                if ((this.FK_idPlayerField.Equals(value) != true)) {
                    this.FK_idPlayerField = value;
                    this.RaisePropertyChanged("FK_idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.Player Player {
            get {
                return this.PlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerField, value) != true)) {
                    this.PlayerField = value;
                    this.RaisePropertyChanged("Player");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan hour {
            get {
                return this.hourField;
            }
            set {
                if ((this.hourField.Equals(value) != true)) {
                    this.hourField = value;
                    this.RaisePropertyChanged("hour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idBanReport {
            get {
                return this.idBanReportField;
            }
            set {
                if ((this.idBanReportField.Equals(value) != true)) {
                    this.idBanReportField = value;
                    this.RaisePropertyChanged("idBanReport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                if ((object.ReferenceEquals(this.reasonField, value) != true)) {
                    this.reasonField = value;
                    this.RaisePropertyChanged("reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendList", Namespace="http://schemas.datacontract.org/2004/07/UNO_DB")]
    [System.SerializableAttribute()]
    public partial class FriendList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_idFriendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.Player PlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.Player Player1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> requestAcceptedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_idFriend {
            get {
                return this.FK_idFriendField;
            }
            set {
                if ((this.FK_idFriendField.Equals(value) != true)) {
                    this.FK_idFriendField = value;
                    this.RaisePropertyChanged("FK_idFriend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_idPlayer {
            get {
                return this.FK_idPlayerField;
            }
            set {
                if ((this.FK_idPlayerField.Equals(value) != true)) {
                    this.FK_idPlayerField = value;
                    this.RaisePropertyChanged("FK_idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.Player Player {
            get {
                return this.PlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerField, value) != true)) {
                    this.PlayerField = value;
                    this.RaisePropertyChanged("Player");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.Player Player1 {
            get {
                return this.Player1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Player1Field, value) != true)) {
                    this.Player1Field = value;
                    this.RaisePropertyChanged("Player1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> requestAccepted {
            get {
                return this.requestAcceptedField;
            }
            set {
                if ((this.requestAcceptedField.Equals(value) != true)) {
                    this.requestAcceptedField = value;
                    this.RaisePropertyChanged("requestAccepted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Match", Namespace="http://schemas.datacontract.org/2004/07/UNO_DB")]
    [System.SerializableAttribute()]
    public partial class Match : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_idLobbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FK_idPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.Lobby LobbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.Player PlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> scoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_idLobby {
            get {
                return this.FK_idLobbyField;
            }
            set {
                if ((this.FK_idLobbyField.Equals(value) != true)) {
                    this.FK_idLobbyField = value;
                    this.RaisePropertyChanged("FK_idLobby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_idPlayer {
            get {
                return this.FK_idPlayerField;
            }
            set {
                if ((this.FK_idPlayerField.Equals(value) != true)) {
                    this.FK_idPlayerField = value;
                    this.RaisePropertyChanged("FK_idPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.Lobby Lobby {
            get {
                return this.LobbyField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbyField, value) != true)) {
                    this.LobbyField = value;
                    this.RaisePropertyChanged("Lobby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.Player Player {
            get {
                return this.PlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerField, value) != true)) {
                    this.PlayerField = value;
                    this.RaisePropertyChanged("Player");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> position {
            get {
                return this.positionField;
            }
            set {
                if ((this.positionField.Equals(value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> score {
            get {
                return this.scoreField;
            }
            set {
                if ((this.scoreField.Equals(value) != true)) {
                    this.scoreField = value;
                    this.RaisePropertyChanged("score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lobby", Namespace="http://schemas.datacontract.org/2004/07/UNO_DB")]
    [System.SerializableAttribute()]
    public partial class Lobby : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FK_idGameModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.GameMode GameModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.Match[] MatchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idLobbyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int matchDurationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FK_idGameMode {
            get {
                return this.FK_idGameModeField;
            }
            set {
                if ((this.FK_idGameModeField.Equals(value) != true)) {
                    this.FK_idGameModeField = value;
                    this.RaisePropertyChanged("FK_idGameMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.GameMode GameMode {
            get {
                return this.GameModeField;
            }
            set {
                if ((object.ReferenceEquals(this.GameModeField, value) != true)) {
                    this.GameModeField = value;
                    this.RaisePropertyChanged("GameMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.Match[] Matches {
            get {
                return this.MatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchesField, value) != true)) {
                    this.MatchesField = value;
                    this.RaisePropertyChanged("Matches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLobby {
            get {
                return this.idLobbyField;
            }
            set {
                if ((this.idLobbyField.Equals(value) != true)) {
                    this.idLobbyField = value;
                    this.RaisePropertyChanged("idLobby");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isPrivate {
            get {
                return this.isPrivateField;
            }
            set {
                if ((this.isPrivateField.Equals(value) != true)) {
                    this.isPrivateField = value;
                    this.RaisePropertyChanged("isPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lobbyCode {
            get {
                return this.lobbyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.lobbyCodeField, value) != true)) {
                    this.lobbyCodeField = value;
                    this.RaisePropertyChanged("lobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int matchDuration {
            get {
                return this.matchDurationField;
            }
            set {
                if ((this.matchDurationField.Equals(value) != true)) {
                    this.matchDurationField = value;
                    this.RaisePropertyChanged("matchDuration");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameMode", Namespace="http://schemas.datacontract.org/2004/07/UNO_DB")]
    [System.SerializableAttribute()]
    public partial class GameMode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UNO_Client.Proxy.Lobby[] LobbiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idGameModesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UNO_Client.Proxy.Lobby[] Lobbies {
            get {
                return this.LobbiesField;
            }
            set {
                if ((object.ReferenceEquals(this.LobbiesField, value) != true)) {
                    this.LobbiesField = value;
                    this.RaisePropertyChanged("Lobbies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idGameModes {
            get {
                return this.idGameModesField;
            }
            set {
                if ((this.idGameModesField.Equals(value) != true)) {
                    this.idGameModesField = value;
                    this.RaisePropertyChanged("idGameModes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.ILoginServices", CallbackContract=typeof(UNO_Client.Proxy.ILoginServicesCallback))]
    public interface ILoginServices {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILoginServices/Login")]
        void Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILoginServices/Login")]
        System.Threading.Tasks.Task LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServices/IsLogged", ReplyAction="http://tempuri.org/ILoginServices/IsLoggedResponse")]
        bool IsLogged(UNO_Client.Proxy.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServices/IsLogged", ReplyAction="http://tempuri.org/ILoginServices/IsLoggedResponse")]
        System.Threading.Tasks.Task<bool> IsLoggedAsync(UNO_Client.Proxy.Player player);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServicesCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServices/LoginVerification", ReplyAction="http://tempuri.org/ILoginServices/LoginVerificationResponse")]
        void LoginVerification(bool result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServicesChannel : UNO_Client.Proxy.ILoginServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServicesClient : System.ServiceModel.DuplexClientBase<UNO_Client.Proxy.ILoginServices>, UNO_Client.Proxy.ILoginServices {
        
        public LoginServicesClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LoginServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LoginServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServicesClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Login(string username, string password) {
            base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool IsLogged(UNO_Client.Proxy.Player player) {
            return base.Channel.IsLogged(player);
        }
        
        public System.Threading.Tasks.Task<bool> IsLoggedAsync(UNO_Client.Proxy.Player player) {
            return base.Channel.IsLoggedAsync(player);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxy.IPlayerManager", CallbackContract=typeof(UNO_Client.Proxy.IPlayerManagerCallback))]
    public interface IPlayerManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/SearchPlayer", ReplyAction="http://tempuri.org/IPlayerManager/SearchPlayerResponse")]
        UNO_Client.Proxy.Player SearchPlayer(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/SearchPlayer", ReplyAction="http://tempuri.org/IPlayerManager/SearchPlayerResponse")]
        System.Threading.Tasks.Task<UNO_Client.Proxy.Player> SearchPlayerAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/EmailAlreadyExist", ReplyAction="http://tempuri.org/IPlayerManager/EmailAlreadyExistResponse")]
        bool EmailAlreadyExist(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/EmailAlreadyExist", ReplyAction="http://tempuri.org/IPlayerManager/EmailAlreadyExistResponse")]
        System.Threading.Tasks.Task<bool> EmailAlreadyExistAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/AddNewPlayer", ReplyAction="http://tempuri.org/IPlayerManager/AddNewPlayerResponse")]
        bool AddNewPlayer(UNO_Client.Proxy.Player newPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/AddNewPlayer", ReplyAction="http://tempuri.org/IPlayerManager/AddNewPlayerResponse")]
        System.Threading.Tasks.Task<bool> AddNewPlayerAsync(UNO_Client.Proxy.Player newPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/DeletePlayer", ReplyAction="http://tempuri.org/IPlayerManager/DeletePlayerResponse")]
        void DeletePlayer(UNO_Client.Proxy.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/DeletePlayer", ReplyAction="http://tempuri.org/IPlayerManager/DeletePlayerResponse")]
        System.Threading.Tasks.Task DeletePlayerAsync(UNO_Client.Proxy.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/ModifyPlayer", ReplyAction="http://tempuri.org/IPlayerManager/ModifyPlayerResponse")]
        void ModifyPlayer(UNO_Client.Proxy.Player player, UNO_Client.Proxy.Player newPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/ModifyPlayer", ReplyAction="http://tempuri.org/IPlayerManager/ModifyPlayerResponse")]
        System.Threading.Tasks.Task ModifyPlayerAsync(UNO_Client.Proxy.Player player, UNO_Client.Proxy.Player newPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetAllPlayers", ReplyAction="http://tempuri.org/IPlayerManager/GetAllPlayersResponse")]
        void GetAllPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetAllPlayers", ReplyAction="http://tempuri.org/IPlayerManager/GetAllPlayersResponse")]
        System.Threading.Tasks.Task GetAllPlayersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/RegisterPlayer", ReplyAction="http://tempuri.org/IPlayerManager/RegisterPlayerResponse")]
        void RegisterPlayer(UNO_Client.Proxy.Player newPlayer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/RegisterPlayer", ReplyAction="http://tempuri.org/IPlayerManager/RegisterPlayerResponse")]
        System.Threading.Tasks.Task RegisterPlayerAsync(UNO_Client.Proxy.Player newPlayer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerManagerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/VerifyPlayerDeletion", ReplyAction="http://tempuri.org/IPlayerManager/VerifyPlayerDeletionResponse")]
        void VerifyPlayerDeletion(bool response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/VerifyPlayerModification", ReplyAction="http://tempuri.org/IPlayerManager/VerifyPlayerModificationResponse")]
        void VerifyPlayerModification(bool response);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/GetPlayersResponse", ReplyAction="http://tempuri.org/IPlayerManager/GetPlayersResponseResponse")]
        void GetPlayersResponse(UNO_Client.Proxy.Player[] players);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPlayerManager/VerifyPlayerRegistration", ReplyAction="http://tempuri.org/IPlayerManager/VerifyPlayerRegistrationResponse")]
        void VerifyPlayerRegistration(bool response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPlayerManagerChannel : UNO_Client.Proxy.IPlayerManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerManagerClient : System.ServiceModel.DuplexClientBase<UNO_Client.Proxy.IPlayerManager>, UNO_Client.Proxy.IPlayerManager {
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerManagerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public UNO_Client.Proxy.Player SearchPlayer(string username) {
            return base.Channel.SearchPlayer(username);
        }
        
        public System.Threading.Tasks.Task<UNO_Client.Proxy.Player> SearchPlayerAsync(string username) {
            return base.Channel.SearchPlayerAsync(username);
        }
        
        public bool EmailAlreadyExist(string email) {
            return base.Channel.EmailAlreadyExist(email);
        }
        
        public System.Threading.Tasks.Task<bool> EmailAlreadyExistAsync(string email) {
            return base.Channel.EmailAlreadyExistAsync(email);
        }
        
        public bool AddNewPlayer(UNO_Client.Proxy.Player newPlayer) {
            return base.Channel.AddNewPlayer(newPlayer);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewPlayerAsync(UNO_Client.Proxy.Player newPlayer) {
            return base.Channel.AddNewPlayerAsync(newPlayer);
        }
        
        public void DeletePlayer(UNO_Client.Proxy.Player player) {
            base.Channel.DeletePlayer(player);
        }
        
        public System.Threading.Tasks.Task DeletePlayerAsync(UNO_Client.Proxy.Player player) {
            return base.Channel.DeletePlayerAsync(player);
        }
        
        public void ModifyPlayer(UNO_Client.Proxy.Player player, UNO_Client.Proxy.Player newPlayer) {
            base.Channel.ModifyPlayer(player, newPlayer);
        }
        
        public System.Threading.Tasks.Task ModifyPlayerAsync(UNO_Client.Proxy.Player player, UNO_Client.Proxy.Player newPlayer) {
            return base.Channel.ModifyPlayerAsync(player, newPlayer);
        }
        
        public void GetAllPlayers() {
            base.Channel.GetAllPlayers();
        }
        
        public System.Threading.Tasks.Task GetAllPlayersAsync() {
            return base.Channel.GetAllPlayersAsync();
        }
        
        public void RegisterPlayer(UNO_Client.Proxy.Player newPlayer) {
            base.Channel.RegisterPlayer(newPlayer);
        }
        
        public System.Threading.Tasks.Task RegisterPlayerAsync(UNO_Client.Proxy.Player newPlayer) {
            return base.Channel.RegisterPlayerAsync(newPlayer);
        }
    }
}
