//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNO_Client.LoginServicesProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginServicesProxy.ILoginServices", CallbackContract=typeof(UNO_Client.LoginServicesProxy.ILoginServicesCallback))]
    public interface ILoginServices {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILoginServices/Login")]
        void Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILoginServices/Login")]
        System.Threading.Tasks.Task LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServices/IsLogged", ReplyAction="http://tempuri.org/ILoginServices/IsLoggedResponse")]
        void IsLogged(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServices/IsLogged", ReplyAction="http://tempuri.org/ILoginServices/IsLoggedResponse")]
        System.Threading.Tasks.Task IsLoggedAsync(string username, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServicesCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServices/LoginVerification", ReplyAction="http://tempuri.org/ILoginServices/LoginVerificationResponse")]
        void LoginVerification(bool result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginServices/IsLoggedResult", ReplyAction="http://tempuri.org/ILoginServices/IsLoggedResultResponse")]
        void IsLoggedResult(bool result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServicesChannel : UNO_Client.LoginServicesProxy.ILoginServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServicesClient : System.ServiceModel.DuplexClientBase<UNO_Client.LoginServicesProxy.ILoginServices>, UNO_Client.LoginServicesProxy.ILoginServices {
        
        public LoginServicesClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LoginServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LoginServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServicesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServicesClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Login(string username, string password) {
            base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public void IsLogged(string username, string password) {
            base.Channel.IsLogged(username, password);
        }
        
        public System.Threading.Tasks.Task IsLoggedAsync(string username, string password) {
            return base.Channel.IsLoggedAsync(username, password);
        }
    }
}
