//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNO_DB
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ReporteMalaConducta
    {
        public int idReporteMalaConducta { get; set; }
        public string razon { get; set; }
        public System.TimeSpan hora { get; set; }
        public System.DateTime fecha { get; set; }
        public int idJugador { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
