//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNO_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UNO_Client.Properties.Language_en", typeof(Language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create a room.
        /// </summary>
        public static string Btn_createRoom {
            get {
                return ResourceManager.GetString("Btn_createRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join a room.
        /// </summary>
        public static string Btn_Join {
            get {
                return ResourceManager.GetString("Btn_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load Image.
        /// </summary>
        public static string btn_LoadImage {
            get {
                return ResourceManager.GetString("btn_LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover password.
        /// </summary>
        public static string btn_PasswordRecovery {
            get {
                return ResourceManager.GetString("btn_PasswordRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string btn_RegisterNewUser {
            get {
                return ResourceManager.GetString("btn_RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best Scorers.
        /// </summary>
        public static string Btn_Scorers {
            get {
                return ResourceManager.GetString("Btn_Scorers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send me the password.
        /// </summary>
        public static string Btn_SendMeEmail {
            get {
                return ResourceManager.GetString("Btn_SendMeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification.
        /// </summary>
        public static string Btn_Verification {
            get {
                return ResourceManager.GetString("Btn_Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audio.
        /// </summary>
        public static string BtnAudio {
            get {
                return ResourceManager.GetString("BtnAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string BtnEnglish {
            get {
                return ResourceManager.GetString("BtnEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string BtnLanguage {
            get {
                return ResourceManager.GetString("BtnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string BtnSpanish {
            get {
                return ResourceManager.GetString("BtnSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string BtnStart {
            get {
                return ResourceManager.GetString("BtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leaving the game/AFK.
        /// </summary>
        public static string CB_Leaving {
            get {
                return ResourceManager.GetString("CB_Leaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negative attitude.
        /// </summary>
        public static string CB_NegativeActtitude {
            get {
                return ResourceManager.GetString("CB_NegativeActtitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verbal Abuse.
        /// </summary>
        public static string CB_VerbalAbuse {
            get {
                return ResourceManager.GetString("CB_VerbalAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lb_LoginError {
            get {
                return ResourceManager.GetString("lb_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All fields marked with * are required.
        /// </summary>
        public static string LbAllFields {
            get {
                return ResourceManager.GetString("LbAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar.
        /// </summary>
        public static string LbAvatar {
            get {
                return ResourceManager.GetString("LbAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a language.
        /// </summary>
        public static string LbChooseLan {
            get {
                return ResourceManager.GetString("LbChooseLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string LbConfirmPassword {
            get {
                return ResourceManager.GetString("LbConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string LbEmail {
            get {
                return ResourceManager.GetString("LbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        public static string LbLastName {
            get {
                return ResourceManager.GetString("LbLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string LbLoggin {
            get {
                return ResourceManager.GetString("LbLoggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name(s).
        /// </summary>
        public static string LbName {
            get {
                return ResourceManager.GetString("LbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string LbPassword {
            get {
                return ResourceManager.GetString("LbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register new user.
        /// </summary>
        public static string LbRegisterNewUser {
            get {
                return ResourceManager.GetString("LbRegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter your email to send you the password.
        /// </summary>
        public static string LbSendEmail {
            get {
                return ResourceManager.GetString("LbSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Name.
        /// </summary>
        public static string LbUserName {
            get {
                return ResourceManager.GetString("LbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verification code.
        /// </summary>
        public static string LbVerification {
            get {
                return ResourceManager.GetString("LbVerification", resourceCulture);
            }
        }
    }
}
